import { HttpEventType } from '@angular/common/http';
import { Component, DestroyRef, inject, input, type OnChanges, output, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { DomSanitizer, type SafeUrl } from '@angular/platform-browser';
import { type Jam, JamService } from '@jam';
import { type ImageCroppedEvent, ImageCropperComponent, type OutputFormat } from 'ngx-image-cropper';
import { base64ArrayBuffer } from '@utils/base64';
import { AdminFolderService } from '@core/services/admin-folder/admin-folder.service';
import { NotifyService } from '@core/services/notify/notify.service';
import { isValidBlobUrl } from '@utils/blob';

export interface ImageEdit {
	artwork: Jam.Artwork;
	folderID: string;
}

@Component({
	selector: 'app-admin-artwork-edit',
	templateUrl: './artwork-edit.component.html',
	styleUrls: ['./artwork-edit.component.scss'],
	imports: [FormsModule, ImageCropperComponent]
})
export class ArtworkEditComponent implements OnChanges {
	readonly data = input<ImageEdit>();
	readonly imageEdited = output();
	readonly imageBase64 = signal('');
	croppedImage?: SafeUrl;
	croppedImageFile?: Blob;
	maintainAspectRatio: boolean = true;
	format: OutputFormat = 'jpeg';
	private readonly lifeRef = inject(DestroyRef);
	private readonly jam = inject(JamService);
	private readonly folderService = inject(AdminFolderService);
	private readonly notify = inject(NotifyService);
	private readonly sanitizer = inject(DomSanitizer);

	load(): void {
		const dataValue = this.data();
		if (dataValue) {
			this.jam.image.imageBinary({ id: dataValue.artwork.id })
				.then(data => {
					this.imageBase64.set(`data:${(data.contentType || 'image/jpeg')};base64,${base64ArrayBuffer(data.buffer)}`);
				})
				.catch((error: unknown) => {
					this.notify.error(error);
				});
		}
	}

	ngOnChanges(): void {
		this.load();
	}

	imageCropped(event: ImageCroppedEvent): void {
		if (event.objectUrl) {
			if (isValidBlobUrl(event.objectUrl)) {
				this.croppedImage = this.sanitizer.bypassSecurityTrustUrl(event.objectUrl);
			} else {
				console.error('Invalid object URL from image cropper:', event.objectUrl);
				this.notify.error('Invalid image URL generated by cropper');
				this.croppedImage = undefined;
			}
		}
		if (event.blob) {
			this.croppedImageFile = event.blob;
		}
	}

	upload(): void {
		const data = this.data();
		if (!data || !this.croppedImageFile) {
			return;
		}
		const folderID = data.folderID;
		const file = new File([this.croppedImageFile], data.artwork.name, { type: this.croppedImageFile.type });
		this.jam.artwork.update({ id: data.artwork.id }, file)
			.pipe(takeUntilDestroyed(this.lifeRef))
			.subscribe({
				next: event => {
					if (event.type !== HttpEventType.Response || event.body === null) {
						return;
					}

					this.folderService.waitForQueueResult('Updating Folder Artwork', event.body, [folderID]);
					this.imageEdited.emit();
				},
				error: error => {
					this.notify.error(error);
				},
				complete: () => {
					this.notify.success('Upload done');
				}
			});
	}
}
