name: debug

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: DEBUG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build:releaselog
      - run: tail -n 100 ./RELEASELOG.md
